/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteRouteImport } from './routes/index.route'
import { Route as GroupsRouteRouteImport } from './routes/groups.route'
import { Route as LogsRouteRouteImport } from './routes/logs.route'
import { Route as QueuesRouteRouteImport } from './routes/queues.route'
import { Route as ScheduledRouteRouteImport } from './routes/scheduled.route'
import { Route as TasksRouteRouteImport } from './routes/tasks.route'
import { Route as WorkersRouteRouteImport } from './routes/workers.route'
import { Route as QueuesQueueNameRouteRouteImport } from './routes/queues_.$queueName.route'

const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRouteRoute = GroupsRouteRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRouteRoute = LogsRouteRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesRouteRoute = QueuesRouteRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduledRouteRoute = ScheduledRouteRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRouteRoute = TasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersRouteRoute = WorkersRouteRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesQueueNameRouteRoute = QueuesQueueNameRouteRouteImport.update({
  id: '/queues_/$queueName',
  path: '/queues/$queueName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/groups': typeof GroupsRouteRoute
  '/logs': typeof LogsRouteRoute
  '/queues': typeof QueuesRouteRoute
  '/scheduled': typeof ScheduledRouteRoute
  '/tasks': typeof TasksRouteRoute
  '/workers': typeof WorkersRouteRoute
  '/queues/$queueName': typeof QueuesQueueNameRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/groups': typeof GroupsRouteRoute
  '/logs': typeof LogsRouteRoute
  '/queues': typeof QueuesRouteRoute
  '/scheduled': typeof ScheduledRouteRoute
  '/tasks': typeof TasksRouteRoute
  '/workers': typeof WorkersRouteRoute
  '/queues/$queueName': typeof QueuesQueueNameRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/groups': typeof GroupsRouteRoute
  '/logs': typeof LogsRouteRoute
  '/queues': typeof QueuesRouteRoute
  '/scheduled': typeof ScheduledRouteRoute
  '/tasks': typeof TasksRouteRoute
  '/workers': typeof WorkersRouteRoute
  '/queues_/$queueName': typeof QueuesQueueNameRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups'
    | '/logs'
    | '/queues'
    | '/scheduled'
    | '/tasks'
    | '/workers'
    | '/queues/$queueName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groups'
    | '/logs'
    | '/queues'
    | '/scheduled'
    | '/tasks'
    | '/workers'
    | '/queues/$queueName'
  id:
    | '__root__'
    | '/'
    | '/groups'
    | '/logs'
    | '/queues'
    | '/scheduled'
    | '/tasks'
    | '/workers'
    | '/queues_/$queueName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  GroupsRouteRoute: typeof GroupsRouteRoute
  LogsRouteRoute: typeof LogsRouteRoute
  QueuesRouteRoute: typeof QueuesRouteRoute
  ScheduledRouteRoute: typeof ScheduledRouteRoute
  TasksRouteRoute: typeof TasksRouteRoute
  WorkersRouteRoute: typeof WorkersRouteRoute
  QueuesQueueNameRouteRoute: typeof QueuesQueueNameRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues': {
      id: '/queues'
      path: '/queues'
      fullPath: '/queues'
      preLoaderRoute: typeof QueuesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduled': {
      id: '/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof ScheduledRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues_/$queueName': {
      id: '/queues_/$queueName'
      path: '/queues/$queueName'
      fullPath: '/queues/$queueName'
      preLoaderRoute: typeof QueuesQueueNameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  GroupsRouteRoute: GroupsRouteRoute,
  LogsRouteRoute: LogsRouteRoute,
  QueuesRouteRoute: QueuesRouteRoute,
  ScheduledRouteRoute: ScheduledRouteRoute,
  TasksRouteRoute: TasksRouteRoute,
  WorkersRouteRoute: WorkersRouteRoute,
  QueuesQueueNameRouteRoute: QueuesQueueNameRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
